# 数据参数
data:
  file_path: "data/c.csv"  # 数据文件路径
  test_size: 0.2                 # 验证集比例
  random_seed: 42                # 随机种子

# 推理参数
inference:
  # 批处理大小 - A10 GPU上可以设置更大的批次大小以提高GPU利用率
  batch_size: 512
  
  # 数据加载的并行工作进程数
  num_workers: 16
  
  # 是否使用自动混合精度 (Automatic Mixed Precision): 有问题别开
  use_amp: true
  
  # 是否使用梯度检查点 (通常在推理阶段不需要，但可以作为控制内存使用的选项)
  use_gradient_checkpointing: false
  

loading:
  trust_remote_code: true
  local_files_only: true

# 模型参数
model:
  bert_model_path: "embed_model"
  feature_dim: 2
  hidden_dim: 64                # 增加到64，提高模型容量
  dropout_rate: 0.3             # 大幅提高dropout，从0.55到0.7
  alpha: 0.4                    # 降低到0.4，减少对困难样本的过度关注
  gamma: 1.5                    # 大幅降低到1.5，减少focal loss的极端效应
  label_smoothing: 0.1          # 增加到0.1，提高泛化能力
  l1: 0.005                     # 降低L1正则化，避免过度稀疏
  l2: 0.015                     # 适度增加L2正则化

# 训练参数 - 稳定性优化
training:
  batch_size: 32                # 减小batch size，提高训练稳定性
  learning_rate: 3e-4           # 进一步降低学习率，从6e-4到3e-4
  num_epochs: 25                # 减少最大轮数，避免过拟合
  patience: 8                   # 适度调整早停耐心值
  max_seq_length: 512

# 设备配置
device: "auto"                   # 可选: "auto", "cuda", "cpu"

# 模型加载参数
loading:
  trust_remote_code: True        # 是否信任远程代码
  local_files_only: True         # 是否只使用本地文件
  